version: '3.8'

services:
  ecommerce:
    build: .
    container_name: ecommerce_app
    ports:
      - "8080:80" # Podrás ver tu app en http://localhost:8080
    environment:
      - ENVIRONMENT=development
      # Buenas prácticas: El código de CodeIgniter debería leer esto en vez de credenciales hardcodeadas
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=secreto123
      - DB_NAME=mi_ecomerce
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: ecommerce_db
    environment:
      MYSQL_ROOT_PASSWORD: secreto123
      MYSQL_DATABASE: mi_ecomerce
    ports:
      - "3306:3306"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /run/mysqld
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d

volumes:
  db_data: