# 1. El PID va a una carpeta temporal
pid /tmp/nginx.pid;

# 2. Bloque obligatorio de eventos
events {
    worker_connections 1024;
}

# 3. Bloque HTTP donde vive tu servidor
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # BIEN DE DEVSECOPS: Enviar todos los temporales a /tmp para no usar permisos root
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path       /tmp/proxy_temp_path;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;

    server {
        listen 8080;
        index index.php index.html;
        
        # Apuntando a la carpeta public de CodeIgniter 4
        root /var/www/html/public; 

        # Ocultar la versión de Nginx por seguridad
        server_tokens off;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }
    }
}